### ISSUE TITLE
I would like to be able to run this in us-west-2.

### ISSUE THREAD

**Issue by MadDataScience** [ContinuumIO/anaconda-ec2#2]
AWS has (finally) made it very easy to copy AMIs from one region to another. Unfortunately, they will not let me copy it (even though it's public) because of an "AMI ownership mismatch". Would you mind copying it to us-west-2 (Oregon)? Thank you.

**Comment by quasiben** [comment]
Hi @eklypse,

Thanks for you interest in Anaconda on EC2.  I'm looking into copying to us-west-2

**Comment by quasiben** [comment]
@eklypse Sorry for the delay.  The easy migrate tool wasn't working for me so I built a new AMI from scratch.  Please enjoy:  ami-a4d64194

**Comment by MadDataScience** [comment]
Hi @quasiben, it seems to work alright but when I tried stopping it, I got:
!!! ERROR - Cluster 'test_anaconda' does not contain any 'stoppable'
!!! ERROR - nodes and can only be terminated. Please use the 'terminate'
!!! ERROR - command instead to destroy the cluster.
Is this a bug? Did I do something wrong?
