### ISSUE TITLE
couldn't connect to host (is disco master running at http://master:8989?)

### ISSUE THREAD

**Issue by MadDataScience** [ContinuumIO/anaconda-ec2#3]
Disco should work, out of the box, right? I'm new to Disco, so this could well be user error, but I'm trying to go through the tutorial at http://discoproject.org/doc/disco/start/tutorial.html  When I try the first tutorial (prepare input data) I get an error saying: 
Unable to access resource (http://master:8989/ddfs/new_blob/bigfile_txt-0?): couldn't connect to host
When I try the second tutorial (write job functions), I get a similar error:
disco.error.CommError: Unable to access resource (http://master:8989/disco/job/new): couldn't connect to host (is disco master running at http://master:8989?)
It looks like disco is not configured correctly on my cluster. I can't tell if that's because of something wrong in the AMI, or in the anaconda_plugin or in my own config file or something else entirely. Please help. Thank you.

**Comment by MadDataScience** [comment]
I don't know if this is related or not, but I tried spinning up a new cluster and got the following errors in the process:

> > > Setting up the cluster...
> > > Configuring hostnames...
> > > 10/10 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Creating cluster user: None (uid: 1003, gid: 1003)
> > > !!! ERROR - command 'groupadd -o -g 1003 disco' failed with status 9   |   0%
> > > !!! ERROR - command 'groupadd -o -g 1003 disco' failed with status 9
> > > !!! ERROR - command 'groupadd -o -g 1003 disco' failed with status 9
> > > !!! ERROR - command 'groupadd -o -g 1003 disco' failed with status 9
> > > !!! ERROR - command 'groupadd -o -g 1003 disco' failed with status 9
> > > !!! ERROR - command 'groupadd -o -g 1003 disco' failed with status 9
> > > !!! ERROR - command 'groupadd -o -g 1003 disco' failed with status 9
> > > !!! ERROR - command 'groupadd -o -g 1003 disco' failed with status 9
> > > !!! ERROR - command 'groupadd -o -g 1003 disco' failed with status 9
> > > !!! ERROR - command 'useradd -o -u 1003 -g 1003 -s `which bash` -m disco' failed with status 6
> > > !!! ERROR - command 'useradd -o -u 1003 -g 1003 -s `which bash` -m disco' failed with status 6
> > > !!! ERROR - command 'useradd -o -u 1003 -g 1003 -s `which bash` -m disco' failed with status 6
> > > !!! ERROR - command 'useradd -o -u 1003 -g 1003 -s `which bash` -m disco' failed with status 6
> > > !!! ERROR - command 'useradd -o -u 1003 -g 1003 -s `which bash` -m disco' failed with status 6
> > > !!! ERROR - command 'useradd -o -u 1003 -g 1003 -s `which bash` -m disco' failed with status 6
> > > !!! ERROR - command 'useradd -o -u 1003 -g 1003 -s `which bash` -m disco' failed with status 6
> > > !!! ERROR - command 'useradd -o -u 1003 -g 1003 -s `which bash` -m disco' failed with status 6
> > > !!! ERROR - command 'useradd -o -u 1003 -g 1003 -s `which bash` -m disco' failed with status 6
> > > !!! ERROR - command 'groupadd -o -g 1003 disco' failed with status 9   |  90%
> > > !!! ERROR - command 'useradd -o -u 1003 -g 1003 -s `which bash` -m disco' failed with status 6
> > > 10/10 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Configuring scratch space for user(s): disco
> > > 10/10 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Configuring /etc/hosts on each node
> > > 10/10 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Starting NFS server on master
> > > Configuring NFS exports path(s):
> > > /home
> > > Mounting all NFS export path(s) on 9 worker node(s)
> > > 9/9 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Setting up NFS took 0.080 mins
> > > Configuring passwordless ssh for root
> > > Configuring passwordless ssh for disco
> > > Shutting down threads...
> > > 20/20 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Configuring SGE...
> > > Configuring NFS exports path(s):
> > > /opt/sge6
> > > Mounting all NFS export path(s) on 9 worker node(s)
> > > 9/9 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Setting up NFS took 0.054 mins
> > > Removing previous SGE installation...
> > > Installing Sun Grid Engine...
> > > 9/9 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Creating SGE parallel environment 'orte'
> > > 10/10 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Adding parallel environment 'orte' to queue 'all.q'
> > > Shutting down threads...
> > > 20/20 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Running plugin anaconda_plugin
> > > !!! ERROR - command 'touch /media/test-master' failed with status 1
> > > !!! ERROR - command 'touch /media/test-node' failed with status 1
> > > !!! ERROR - command 'touch /media/test-node' failed with status 1
> > > !!! ERROR - command 'touch /media/test-node' failed with status 1
> > > !!! ERROR - command 'touch /media/test-node' failed with status 1
> > > !!! ERROR - command 'touch /media/test-node' failed with status 1
> > > !!! ERROR - command 'touch /media/test-node' failed with status 1
> > > !!! ERROR - command 'touch /media/test-node' failed with status 1
> > > !!! ERROR - command 'touch /media/test-node' failed with status 1
> > > !!! ERROR - command 'touch /media/test-node' failed with status 1
> > > !!! ERROR - command '/etc/init.d/disco start' failed with status 1
> > > node001
> > > scp ~disco/.ssh/id_rsa.pub node001:~disco/.ssh/authorized_keys
> > > !!! ERROR - command 'scp ~disco/.erlang.cookie node001:~disco/' failed with status 1
> > > node002
> > > scp ~disco/.ssh/id_rsa.pub node002:~disco/.ssh/authorized_keys
> > > !!! ERROR - command 'scp ~disco/.erlang.cookie node002:~disco/' failed with status 1
> > > node003
> > > scp ~disco/.ssh/id_rsa.pub node003:~disco/.ssh/authorized_keys
> > > !!! ERROR - command 'scp ~disco/.erlang.cookie node003:~disco/' failed with status 1
> > > node004
> > > scp ~disco/.ssh/id_rsa.pub node004:~disco/.ssh/authorized_keys
> > > !!! ERROR - command 'scp ~disco/.erlang.cookie node004:~disco/' failed with status 1
> > > node005
> > > scp ~disco/.ssh/id_rsa.pub node005:~disco/.ssh/authorized_keys
> > > !!! ERROR - command 'scp ~disco/.erlang.cookie node005:~disco/' failed with status 1
> > > node006
> > > scp ~disco/.ssh/id_rsa.pub node006:~disco/.ssh/authorized_keys
> > > !!! ERROR - command 'scp ~disco/.erlang.cookie node006:~disco/' failed with status 1
> > > node007
> > > scp ~disco/.ssh/id_rsa.pub node007:~disco/.ssh/authorized_keys
> > > !!! ERROR - command 'scp ~disco/.erlang.cookie node007:~disco/' failed with status 1
> > > node008
> > > scp ~disco/.ssh/id_rsa.pub node008:~disco/.ssh/authorized_keys
> > > !!! ERROR - command 'scp ~disco/.erlang.cookie node008:~disco/' failed with status 1
> > > node009
> > > scp ~disco/.ssh/id_rsa.pub node009:~disco/.ssh/authorized_keys
> > > !!! ERROR - command 'scp ~disco/.erlang.cookie node009:~disco/' failed with status 1
> > > !!! ERROR - command '/etc/init.d/disco start' failed with status 1

**Comment by quasiben** [comment]
That error looks you defined the cluster_user in the startcluster config file to be disco
something like:
CLUSTER_USER = disco

If this is the case, please change CLUSTER_USER to something other than disco.  Perhaps we can chat in real-time and I can help you get your issues resolved?

**Comment by MadDataScience** [comment]
That would be great. I'll start by renaming cluster_user though. I'm noticing you've made a number of changes since I last downloaded this repo actually, so I'll start by updating that. (Sorry for not doing that before opening this issue. I should have been sure to update first. I will be sure to close it if it turns out that was all I needed.)

**Comment by quasiben** [comment]
I sent you a g+ request

**Comment by MadDataScience** [comment]
I'm not seeing the g+ request. But updating the files and changing the cluster_user name did the trick as far as disco is concerned. No more errors either. https://github.com/ContinuumIO/anaconda-ec2/issues/4 is still an issue though.
