### ISSUE TITLE
should be stoppable

### ISSUE THREAD

**Issue by MadDataScience** [ContinuumIO/anaconda-ec2#6]
When I try to stop an anaconda cluster, I get:

!!! ERROR - Cluster 'anaconda_cluster' does not contain any 'stoppable'
!!! ERROR - nodes and can only be terminated. Please use the 'terminate'
!!! ERROR - command instead to destroy the cluster.

This is extremely annoying because I don't like wasting money keeping the cluster running when I'm not at work but starting a new one takes hours because of all the packages I install.

**Comment by quasiben** [comment]
Good point.  I write in the stop function tonight.

**Comment by sjobeek** [comment]
I'm also interested in being able to stop these instances.  Has the stop function been implemented yet?

**Comment by jtriley** [comment]
There is no 'stop' function to be implemented here. This error is related to the fact that the AMIs you're using are S3-backed (or instance-store) and not EBS-backed. Simpy switching to an EBS-backed AMI will allow the cluster to be stoppable.

**Comment by jtriley** [comment]
@eklypse Also, if you're spending hours building/installing packages every time you start a cluster I would **highly** recommend rebundling your own AMI using StarCluster's `ebsimage` command[1]. Starting a cluster should ideally be less than 10min at the most.

[1] http://star.mit.edu/cluster/docs/0.94/manual/create_new_ami.html

**Comment by MadDataScience** [comment]
Thanks!
